### ISSUE TITLE
Cannot generate JUnit XML with new Xcode 11.2

### ISSUE THREAD

**Issue by skoppula018** [nacuteodor/ProcessTestSummaries#18]
We have been using this tool in order to generate junit xml for jenkins to publish the xcode results. We now use Xcode 11.2 for test builds and cannot make this tool to work. 

```
./ProcessTestSummaries --logsTestPath ${derived_data_path}/Logs/Test --jUnitReportPath test.xml
```

output :
```
Parsed options: ["logsTestPath": "XXX/derived_data_path/Logs/Test", "jUnitReportPath": "test.xml"]
Generate JUnit report xml file from XXX/derived_data_path/Logs/Test logs test folder to test.xml file
```
the junit xml [test.xml] is not created even though the output displays successful stats.
 
Can someone kindly let me know as whether I am missing anything here. I am using the latest release version of this tool

**Comment by nacuteodor** [comment]
@skoppula018 I am not using Xcode 11.2 yet, but 11.0 and 11.1. But if you could send me the Test folder, I could try debugging it. The output doesn't say anything about successful. It just doesn't seem to find any test result.

**Comment by nacuteodor** [comment]
ping @skoppula018

**Comment by nacuteodor** [comment]
@skoppula018 Fixed this in https://github.com/nacuteodor/ProcessTestSummaries/pull/19 should work for Xcode 11.3 now. Closing.

**Comment by skoppula018** [comment]
Thank you for looking into the issue @nacuteodor

**Comment by nacuteodor** [comment]
@skoppula018 Make sure you use something similar to --logsTestPath $DERIVED_DATA_PATH/Logs/Test/*.xcresult  or --logsTestPath $DERIVED_DATA_PATH/Logs/Test in the command

**Comment by skoppula018** [comment]
@nacuteodor Got it , Sounds good to me. I am going to try things out with this fix soon
