### ISSUE TITLE
Unable to open application

### ISSUE THREAD

**Issue by jamielee0513** [nacuteodor/ProcessTestSummaries#2]
Last login: Wed Sep 21 13:56:43 on ttys005
/Users/jamie.lee/Downloads/ProcessTestSummaries-1.0.2/Build/Products/Release/ProcessTestSummaries ; exit;
➜  ~ /Users/jamie.lee/Downloads/ProcessTestSummaries-1.0.2/Build/Products/Release/ProcessTestSummaries ; exit;
Parsed options: [:]
[Error] InvalidArgument(" --logsTestPath option value was not found.")
fatal error: 'try!' expression unexpectedly raised an error: ProcessTestSummaries.CustomErrorType.InvalidArgument(" --logsTestPath option value was not found."): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.1/src/swift/stdlib/public/core/ErrorType.swift, line 54
[1]    68970 illegal hardware instruction  

[Process completed]

**Comment by nacuteodor** [comment]
@jamielee0513 What command did you execute? Please, look on the "Usage" section from README page about what arguments you have to pass to ProcessTestSummaries command. It doesn't seem you passed any argument! Closing.
