### ISSUE TITLE
How should I use this tool

### ISSUE THREAD

**Issue by aditjain** [nacuteodor/ProcessTestSummaries#5]
Seems like a nice tool, can you tell me how to start using it. I am newbie to ios xctest and now going to parse testsummaries file to junit xml report. I wrote my own parser but I am now thinking of using your tool since it already does the job.

1- I dont see this working : 
LM-?XXX-11010320:Logs aditjain$ sudo gem install ProcessTestSummaries
ERROR:  Could not find a valid gem 'ProcessTestSummaries' (>= 0) in any repository

2- Should i clone this project in order to use it???

3- Should i include this as a pod in libraries??

3- 2 and 3 above does not work for me since I want to use it from jenkins, 

please help;

**Comment by nacuteodor** [comment]
Hi,

You could clone this project in your job script. And then run the executable which is in repo.
Or you could upload the executable file archive to a builds repo like nexus and download it from there in the job script. Also, using the following command to download the binary file from repo, might work: 
curl -LOk https://raw.githubusercontent.com/nacuteodor/ProcessTestSummaries/master/Build/Products/Release/ProcessTestSummaries   

-Teodor
