### ISSUE TITLE
How to run it exactly?

### ISSUE THREAD

**Issue by phynet** [nacuteodor/ProcessTestSummaries#9]
Hi, I'm interested in your code. But I'm not understanding how to run it. I mean, what is `$LAST_SCREENSHOTS_PATH` and `$BUILD_URL` ? could you improve the readme? 😄 Should I import the project? Or...something else I don't figure out?
Thank you!

**Comment by nacuteodor** [comment]
Hey @phynet 

$LAST_SCREENSHOTS_PATH  is the path where you want to save the last screenshots for each test in a separate folder for each test.  
$BUILD_URL is the name of the Jenkins variable which is the base URL for the screenshots artifacts that are uploaded in the Jenkins job that runs the tests. This can be used to show, in the Jenkins test failure report, links to the screenshots uploaded in the Jenkins job node.

It should be easy to run it by just cloning the repo, and using https://github.com/nacuteodor/ProcessTestSummaries/blob/master/Build/Products/Release/ProcessTestSummaries executable file after running the tests in Jenkins job. You can upload this in Nexus repo or other library repo and download it from there.

Thanks!

**Comment by phynet** [comment]
Thank you, later I read the code and saw it was meant it to run using jenkins directories. I will try it later, to see how it works.  👍 good job

**Comment by nacuteodor** [comment]
Thank you @phynet! I hope this will help you investigate the failures easier, too. I am glad to see this helps!
